-- =========================================================
-- ESQUEMA
-- =========================================================
CREATE SCHEMA IF NOT EXISTS hotel;
SET search_path TO hotel;

CREATE TABLE IF NOT EXISTS persona (
    id_persona BIGINT PRIMARY KEY,
    primer_nombre VARCHAR(50) NOT NULL,
    segundo_nombre VARCHAR(50),
    primer_apellido VARCHAR(50) NOT NULL,
    segundo_apellido VARCHAR(50),
    email VARCHAR(120) NOT NULL UNIQUE,
    calle VARCHAR(100),
    carrera VARCHAR(100),
    numero VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS telefono (
    id_telefono INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona BIGINT NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
        ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE (id_persona, telefono)
);

-- El cliente usa exactamente el mismo id de persona
CREATE TABLE IF NOT EXISTS cliente (
    id_persona BIGINT PRIMARY KEY,
    FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- El empleado usa exactamente el mismo id de persona
CREATE TABLE IF NOT EXISTS empleado (
    id_persona BIGINT PRIMARY KEY,
    cargo VARCHAR(80) NOT NULL,
    area VARCHAR(80) NOT NULL,
    FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS habitacion (
    numero_h INT PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Disponible',
    precio_noche NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS reserva (
    id_reserva INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    numero_h INT NOT NULL,
    fecha_llegada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    valor_reserva NUMERIC(10,2) NOT NULL,
    tiempo_maxc INT NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_persona),
    FOREIGN KEY (numero_h) REFERENCES habitacion(numero_h)
);

CREATE TABLE IF NOT EXISTS servicio (
    id_servicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    costo NUMERIC(10,2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo'
);

CREATE TABLE IF NOT EXISTS consumo (
    id_consumo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva INT NOT NULL,
    id_servicio INT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva),
    FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio)
);
