-- =========================================================
-- ESQUEMA
-- =========================================================
CREATE SCHEMA IF NOT EXISTS hotel;
SET search_path TO hotel;

-- =========================================================
-- TABLA: PERSONA
-- =========================================================
CREATE TABLE IF NOT EXISTS persona (
    id_persona       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primer_nombre    VARCHAR(50)  NOT NULL,
    segundo_nombre   VARCHAR(50),
    primer_apellido  VARCHAR(50)  NOT NULL,
    segundo_apellido VARCHAR(50),
    email            VARCHAR(120)  NOT NULL UNIQUE,
    calle            VARCHAR(100),
    carrera          VARCHAR(100),
    numero           VARCHAR(20)
);

-- =========================================================
-- TABLA: TELEFONO
-- =========================================================
CREATE TABLE IF NOT EXISTS telefono (
    id_telefono INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona  INT NOT NULL,
    telefono    VARCHAR(20) NOT NULL,
    CONSTRAINT fk_telefono_persona
        FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT uk_telefono_persona UNIQUE (id_persona, telefono)
);

-- =========================================================
-- TABLA: CLIENTE
-- =========================================================
CREATE TABLE IF NOT EXISTS cliente (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona INT NOT NULL UNIQUE,
    CONSTRAINT fk_cliente_persona
        FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =========================================================
-- TABLA: EMPLEADO
-- =========================================================
CREATE TABLE IF NOT EXISTS empleado (
    id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona  INT NOT NULL UNIQUE,
    cargo       VARCHAR(80) NOT NULL,
    area        VARCHAR(80) NOT NULL,
    CONSTRAINT fk_empleado_persona
        FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =========================================================
-- TABLA: HABITACION
-- =========================================================
CREATE TABLE IF NOT EXISTS habitacion (
    numero_h     INT PRIMARY KEY,
    tipo         VARCHAR(20) NOT NULL,
    estado       VARCHAR(20) NOT NULL DEFAULT 'Disponible',
    precio_noche NUMERIC(10,2) NOT NULL,
    CONSTRAINT chk_habitacion_tipo
        CHECK (tipo IN ('Sencilla', 'Doble', 'Suite')),
    CONSTRAINT chk_habitacion_estado
        CHECK (estado IN ('Disponible', 'Ocupada', 'Mantenimiento')),
    CONSTRAINT chk_habitacion_precio
        CHECK (precio_noche >= 0)
);

-- =========================================================
-- TABLA: RESERVA
-- =========================================================
CREATE TABLE IF NOT EXISTS reserva (
    id_reserva            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente            INT NOT NULL,
    numero_h              INT NOT NULL,
    fecha_llegada         DATE NOT NULL,
    fecha_salida          DATE NOT NULL,
    valor_reserva         NUMERIC(10,2) NOT NULL,
    tiempo_maxc           INT NOT NULL,
    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_habitacion
        FOREIGN KEY (numero_h) REFERENCES habitacion(numero_h)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_reserva_fechas
        CHECK (fecha_salida >= fecha_llegada),
    CONSTRAINT chk_reserva_valor
        CHECK (valor_reserva >= 0),
    CONSTRAINT chk_reserva_tiempo
        CHECK (tiempo_maxc >= 0)
);

-- =========================================================
-- TABLA: SERVICIO
-- =========================================================
CREATE TABLE IF NOT EXISTS servicio (
    id_servicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    costo       NUMERIC(10,2) NOT NULL,
    estado      VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT chk_servicio_costo
        CHECK (costo >= 0),
    CONSTRAINT chk_servicio_estado
        CHECK (estado IN ('Activo', 'Inactivo'))
);

-- =========================================================
-- TABLA: CONSUMO
-- Registra la reserva, el servicio y la fecha/hora exacta
-- =========================================================
CREATE TABLE IF NOT EXISTS consumo (
    id_consumo  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva   INT NOT NULL,
    id_servicio  INT NOT NULL,
    fecha_hora   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consumo_reserva
        FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_consumo_servicio
        FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
